### ISSUE TITLE
First Release

### ISSUE THREAD

**Issue by azu** [textlint/editor#23]
It is a meta issue.

Milestone for the first release

- [x] Drop kv-storage #20 
- [ ] Startup Guide
  - Default Rule or Initial instruction
  - I think that it require Google Chrome Store
- [x] Rule Developer Guide
  - https://github.com/textlint/editor-script-template 
- [x] Ignore error #12
- [ ] Documentation handling
- [x] Make logger debug mode

**Comment by azu** [comment]
Firefox version is published as beta https://addons.mozilla.org/ja/firefox/addon/textlint-editor/

**Comment by azu** [comment]
Chrome version is available https://chrome.google.com/webstore/detail/textlint-editor/gfhlfpnpjokocfohicmfbgjneiipfeil


Yes, We have published first version! 🎉
